### ISSUE TITLE
How to run UniFunc?

### ISSUE THREAD

**Issue by jolespin** [PedroMTQ/UniFunc#1]
I'm not sure how to run `UniFunc`. There is no executable called `UniFunc`. I fixed the syntax error in the `setup.py` but when I do that, it still doesn't put `UniFunc` in my path. 

Can you create a new environment and make sure none of the steps are missing?

#### Downloading it from GitHub
```
(base) jespinoz@jespinozlt2-osx ~ % git clone https://github.com/PedroMTQ/UniFunc/
Cloning into 'UniFunc'...
remote: Enumerating objects: 145, done.
remote: Counting objects: 100% (145/145), done.
remote: Compressing objects: 100% (102/102), done.
remote: Total 145 (delta 64), reused 116 (delta 39), pack-reused 0
Receiving objects: 100% (145/145), 22.43 MiB | 5.16 MiB/s, done.
Resolving deltas: 100% (64/64), done.
(base) jespinoz@jespinozlt2-osx ~ % cd UniFunc
(base) jespinoz@jespinozlt2-osx UniFunc % ls
Images		LICENSE		README.md	Resources	Workflows	__main__.py	conda-recipe	pyproject.toml	setup.py	source.py	unifunc_env.yml
```

#### Creating the conda environment
```
(base) jespinoz@jespinozlt2-osx UniFunc % conda env create -f unifunc_env.yml -n unifunc_env
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 4.11.0

Please update conda by running

    $ conda update -n base conda



Downloading and Extracting Packages
requests-2.24.0      | 54 KB     | ############################################################################################################################################################################################################# | 100%
xz-5.2.5             | 282 KB    | ############################################################################################################################################################################################################# | 100%
openssl-1.1.1h       | 3.4 MB    | ############################################################################################################################################################################################################# | 100%
ca-certificates-2020 | 127 KB    | ############################################################################################################################################################################################################# | 100%
readline-8.0         | 397 KB    | ############################################################################################################################################################################################################# | 100%
setuptools-50.3.0    | 939 KB    | ############################################################################################################################################################################################################# | 100%
blas-1.0             | 5 KB      | ############################################################################################################################################################################################################# | 100%
pysocks-1.7.1        | 27 KB     | ############################################################################################################################################################################################################# | 100%
sqlite-3.33.0        | 2.5 MB    | ############################################################################################################################################################################################################# | 100%
urllib3-1.25.11      | 93 KB     | ############################################################################################################################################################################################################# | 100%
python-3.8.5         | 25.1 MB   | ############################################################################################################################################################################################################# | 100%
pyopenssl-19.1.0     | 47 KB     | ############################################################################################################################################################################################################# | 100%
six-1.15.0           | 13 KB     | ############################################################################################################################################################################################################# | 100%
ncurses-6.2          | 1016 KB   | ############################################################################################################################################################################################################# | 100%
libffi-3.3           | 48 KB     | ############################################################################################################################################################################################################# | 100%
wheel-0.35.1         | 36 KB     | ############################################################################################################################################################################################################# | 100%
pycparser-2.20       | 94 KB     | ############################################################################################################################################################################################################# | 100%
brotlipy-0.7.0       | 357 KB    | ############################################################################################################################################################################################################# | 100%
intel-openmp-2020.2  | 1.2 MB    | ############################################################################################################################################################################################################# | 100%
cffi-1.14.3          | 219 KB    | ############################################################################################################################################################################################################# | 100%
mkl_fft-1.2.0        | 162 KB    | ############################################################################################################################################################################################################# | 100%
chardet-3.0.4        | 170 KB    | ############################################################################################################################################################################################################# | 100%
certifi-2020.6.20    | 159 KB    | ############################################################################################################################################################################################################# | 100%
cryptography-3.1.1   | 604 KB    | ############################################################################################################################################################################################################# | 100%
tqdm-4.50.2          | 55 KB     | ############################################################################################################################################################################################################# | 100%
libedit-3.1.20191231 | 102 KB    | ############################################################################################################################################################################################################# | 100%
tk-8.6.10            | 3.3 MB    | ############################################################################################################################################################################################################# | 100%
idna-2.10            | 56 KB     | ############################################################################################################################################################################################################# | 100%
nltk-3.5             | 1.1 MB    | ############################################################################################################################################################################################################# | 100%
joblib-0.17.0        | 205 KB    | ############################################################################################################################################################################################################# | 100%
zlib-1.2.11          | 105 KB    | ############################################################################################################################################################################################################# | 100%
click-7.1.2          | 67 KB     | ############################################################################################################################################################################################################# | 100%
mkl-service-2.3.0    | 46 KB     | ############################################################################################################################################################################################################# | 100%
numpy-base-1.19.1    | 5.1 MB    | ############################################################################################################################################################################################################# | 100%
mkl_random-1.1.1     | 337 KB    | ############################################################################################################################################################################################################# | 100%
mkl-2019.4           | 155.2 MB  | ############################################################################################################################################################################################################# | 100%
libcxx-10.0.0        | 1.0 MB    | ############################################################################################################################################################################################################# | 100%
regex-2020.10.15     | 349 KB    | ############################################################################################################################################################################################################# | 100%
numpy-1.19.1         | 20 KB     | ############################################################################################################################################################################################################# | 100%
pip-20.2.4           | 2.0 MB    | ############################################################################################################################################################################################################# | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate unifunc_env
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) jespinoz@jespinozlt2-osx UniFunc % conda activate unifunc_env
```

#### Python version
```
(unifunc_env) jespinoz@jespinozlt2-osx UniFunc % which python
/Users/jespinoz/anaconda3/envs/unifunc_env/bin/python
(unifunc_env) jespinoz@jespinozlt2-osx UniFunc % python --version
Python 3.8.5
```

#### Tried the setup script
```
(unifunc_env) jespinoz@jespinozlt2-osx UniFunc % python setup.py install
  File "setup.py", line 21
    install_requires=['nltk','numpy','python>=3.6','requests']
    ^
SyntaxError: invalid syntax
```

#### Tried the suggested command: 
```
(unifunc_env) jespinoz@jespinozlt2-osx UniFunc % python UniFunc -h
python: can't open file 'UniFunc': [Errno 2] No such file or directory
(unifunc_env) jespinoz@jespinozlt2-osx UniFunc % python __main__.py -h
Traceback (most recent call last):
  File "__main__.py", line 6, in <module>
    from UniFunc import run_unifunc,run_example
ModuleNotFoundError: No module named 'UniFunc'
```

**Comment by PedroMTQ** [comment]
Hello @jolespin 
You dont' need to run setup.py.

Anyhow, I fixed a bug in the __main__.py, but I think you're doing everything correctly.
could you try running it again?

Regards,
Pedro

**Comment by jolespin** [comment]
Got it!  So `UniFunc` isn't an executable and is a directory instead: 

```
(unifunc_env) jespinoz@jespinozlt2-osx UniFunc % pwd
/Users/jespinoz/UniFunc
(unifunc_env) jespinoz@jespinozlt2-osx UniFunc % python . -h
usage: . [-h] [-v] [-o OUTPUT] [-t THRESHOLD] str1 str2

 _   _         _  _____
| | | |       (_)|  ___|
| | | | _ __   _ | |_    _   _  _ __    ___
| | | || '_ \ | ||  _|  | | | || '_ \  / __|
| |_| || | | || || |    | |_| || | | || (__
 \___/ |_| |_||_|\_|     \__,_||_| |_| \___|, a functional annotation text similarity analysis tool.

UniFunc can be run in two modes:
The default mode returns the similarity score (float) between the provided strings, to run it use: <python UniFunc "this is string1" "this is string2">
The secondary mode requires the user to set a threshold (e.g. 0.95), and True will be returned if the string similarity is above the threshold, and False otherwise. To run it use: <python UniFunc string1 string2 -t 0.95>
To use verbose mode add <-v>, to redirect output to a file, add <-t file_path>

positional arguments:
  str1
  str2

optional arguments:
  -h, --help            show this help message and exit
  -v, --verbose         Verbose mode for UniFunc
  -o OUTPUT, --output OUTPUT
                        File path for console output
  -t THRESHOLD, --threshold THRESHOLD
                        Threshold for similarity analysis
```

I've never seen a program setup like this before but I'm glad it all works out.

**Comment by PedroMTQ** [comment]
Hello @jolespin 
Sorry for the confusion.
Glad it all worked out.

Regards,
Pedro

**Comment by PedroMTQ** [comment]
Hello @jolespin 
You can now install unifunc with conda. 
To run it just do `unifunc -h` and `unifunc cluster_function -h` for the base unifunc and workflow, respectively.

Regards,
Pedro

**Comment by jolespin** [comment]
Looks good to me!

Can't wait to implement this into some pipelines here at JCVI. 

I will make sure if anyone uses is that you will be properly cited. 

```python
(unifunc_env) -bash-4.2$ which unifunc
/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/unifunc_env/bin/unifunc
(unifunc_env) -bash-4.2$ unifunc -h
usage: unifunc [-h] [-v] [-o OUTPUT] [-t THRESHOLD] str1 str2

 _   _         _  _____
| | | |       (_)|  ___|
| | | | _ __   _ | |_    _   _  _ __    ___
| | | || '_ \ | ||  _|  | | | || '_ \  / __|
| |_| || | | || || |    | |_| || | | || (__
 \___/ |_| |_||_|\_|     \__,_||_| |_| \___|, a functional annotation text similarity analysis tool.

UniFunc can be run in two modes:
The default mode returns the similarity score (float) between the provided strings, to run it use: <python UniFunc "this is string1" "this is string2">
The secondary mode requires the user to set a threshold (e.g. 0.95), and True will be returned if the string similarity is above the threshold, and False otherwise. To run it use: <python UniFunc string1 string2 -t 0.95>
To use verbose mode add <-v>, to redirect output to a file, add <-t file_path>

positional arguments:
  str1
  str2

optional arguments:
  -h, --help            show this help message and exit
  -v, --verbose         Verbose mode for UniFunc
  -o OUTPUT, --output OUTPUT
                        File path for console output
  -t THRESHOLD, --threshold THRESHOLD
                        Threshold for similarity analysis
(unifunc_env) -bash-4.2$
(unifunc_env) -bash-4.2$ unifunc cluster_function -h
usage: unifunc [-h] [-i INPUT_PATH] [-o OUTPUT_FOLDER] [-v]
               [-st SIMILARITY_THRESHOLD] [-kh] [-ra] [-uw UNANNOTATED_WEIGHT]
               [-rt REPRESENTATIVE_THRESHOLD] [-owr]
               workflow

positional arguments:
  workflow

optional arguments:
  -h, --help            show this help message and exit
  -i INPUT_PATH, --input_path INPUT_PATH
                        [required]	Input with a tsv of clusters formatted as: gene_id|cluster|annotation. The tsv should be sorted by cluster! Otherwise this code will not work properly.
  -o OUTPUT_FOLDER, --output_folder OUTPUT_FOLDER
                        [required]	Output folder path
  -v, --verbose         Verbose mode for UniFunc. Default is False
  -st SIMILARITY_THRESHOLD, --similarity_threshold SIMILARITY_THRESHOLD
                        Threshold for similarity analysis.Default is 0.8
  -kh, --keep_hypothetical
                        Consider hypothetical annotations as not being annotations? Default is False
  -ra, --remove_unannotated
                        Consider unannotations (i.e., blank functions) in the scording system? Default is False
  -uw UNANNOTATED_WEIGHT, --unannotated_weight UNANNOTATED_WEIGHT
                        Weight for unannotations (i.e., blank functions) in the scording system? Default is 0.5
  -rt REPRESENTATIVE_THRESHOLD, --representative_threshold REPRESENTATIVE_THRESHOLD
                        Score to consider a function representative? Default is 0.8
  -owr, --output_without_representative
                        Output clusters without a representative function? Default is False
```

**Comment by PedroMTQ** [comment]
@jolespin 
Great, I'm glad it will be put to use. Let me know if need me to change anything ;)

Regards,
Pedro
