### ISSUE TITLE
TypeError: _pos_tag() got an unexpected keyword argument 'lang'

### ISSUE THREAD

**Issue by jolespin** [PedroMTQ/UniFunc#3]
Apologies for all of the issues as of late. I had trouble running the `conda` installation: 

Here's my conda environment
```bash
(unifunc_env) -bash-4.2$ conda list
# packages in environment at /usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/unifunc_env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
certifi                   2016.9.26                py36_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libblas                   3.9.0           12_linux64_openblas    conda-forge
libcblas                  3.9.0           12_linux64_openblas    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libgfortran-ng            11.2.0              h69a702a_11    conda-forge
libgfortran5              11.2.0              h5c6108e_11    conda-forge
libgomp                   11.2.0              h1d223b6_11    conda-forge
liblapack                 3.9.0           12_linux64_openblas    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nltk                      3.2.4                    py36_0    conda-forge
numpy                     1.19.5           py36hfc0c790_2    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
python                    3.6.15          hb7a2778_0_cpython    conda-forge
python_abi                3.6                     2_cp36m    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.12.5                   py36_0    conda-forge
setuptools                49.6.0           py36h5fab9bb_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.37.0               h9cd32fc_0    conda-forge
tk                        8.6.11               h27826a3_1    conda-forge
unifunc                   1.3.4              pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
```

Here's my sample command: 
```
(unifunc_env) -bash-4.2$ unifunc cluster_function -i sample.tsv -o unifunc_output/ -kh
Traceback (most recent call last):
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/unifunc_env/bin/unifunc", line 10, in <module>
    sys.exit(main())
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/unifunc_env/lib/python3.6/site-packages/unifunc/__main__.py", line 84, in main
    argv_cluster_representative_function()
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/unifunc_env/lib/python3.6/site-packages/unifunc/__main__.py", line 73, in argv_cluster_representative_function
    output_without_representative=output_without_representative,
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/unifunc_env/lib/python3.6/site-packages/Workflows/Representative_function/Cluster_Representative_Function.py", line 27, in __init__
    self.unifunc = source.UniFunc()
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/unifunc_env/lib/python3.6/site-packages/unifunc/source.py", line 1062, in __init__
    self.wordnet_tagger = WordNetTagger(go_terms=self.go_terms, perceptron_tagger=self.tagger)
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/unifunc_env/lib/python3.6/site-packages/unifunc/source.py", line 732, in __init__
    if self.tag_tokens_perceptron([g]) not in ['ADP','CONJ','DET','PRON','PRT']:
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/unifunc_env/lib/python3.6/site-packages/unifunc/source.py", line 740, in tag_tokens_perceptron
    return _pos_tag(tokens, tagset='universal', tagger=self.perceptron_tagger,lang='eng')
TypeError: _pos_tag() got an unexpected keyword argument 'lang'
```

**Comment by jolespin** [comment]
Fixed it. I just did `conda install python=3.9` (py3.6 was installed originally with the conda recipe) and then I had to redownload the `nltk` db: 

```python
(unifunc_env) -bash-4.2$ python
Python 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:40:17)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>> nltk.download('omw-1.4', '/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/unifunc_env/nltk_data')
[nltk_data] Downloading package omw-1.4 to /usr/local/devel/ANNOTATION
[nltk_data]     /jespinoz/anaconda3/envs/unifunc_env/nltk_data...
[nltk_data]   Unzipping corpora/omw-1.4.zip.
True
```

**Comment by PedroMTQ** [comment]
Thanks for letting me know! I'll update the recipe.

Regards,
Pedro
